version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - POCKETBASE_URL=${POCKETBASE_URL:-http://pocketbase:8081}
    depends_on:
      - pocketbase
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/coollabsio/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8081:8080"
    volumes:
      - ./pocketbase/data:/pb_data
      - ./pocketbase/public:/pb/pb_public
      - ./pocketbase/migrations:/pb/pb_migrations

    restart: unless-stopped
